version: "3.9"

services:
  geoguesser:
    build: .
    container_name: geoguesser
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
